// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoExpandTextareaController from "./auto_expand_textarea_controller"
application.register("auto-expand-textarea", AutoExpandTextareaController)

import AutosubmitselectController from "./autosubmitselect_controller"
application.register("autosubmitselect", AutosubmitselectController)

import ChangeController from "./change_controller"
application.register("change", ChangeController)

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import MaskController from "./mask_controller"
application.register("mask", MaskController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
