ARG RUBY_VERSION=3.3.1
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION

RUN sudo apt-get update && sudo apt-get install -y openvpn
RUN sudo apt-get update && sudo apt-get install -y firebird-dev firebird-utils
